// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SRC_Travel_Agencies.Context;

#nullable disable

namespace SRC_Travel_Agencies.Migrations
{
    [DbContext(typeof(SqlContext))]
    [Migration("20240304174813_m")]
    partial class m
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SRC_Travel_Agencies.Models.Bus_Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Upload_BusBus_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Upload_BusBus_id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("SRC_Travel_Agencies.Models.Upload_Bus", b =>
                {
                    b.Property<int>("Bus_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Bus_id"));

                    b.Property<string>("Bus_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Bus_price")
                        .HasColumnType("int");

                    b.Property<int>("category_Id")
                        .HasColumnType("int");

                    b.HasKey("Bus_id");

                    b.HasIndex("category_Id");

                    b.ToTable("uploads");
                });

            modelBuilder.Entity("SRC_Travel_Agencies.Models.Bus_Category", b =>
                {
                    b.HasOne("SRC_Travel_Agencies.Models.Upload_Bus", null)
                        .WithMany("Categories")
                        .HasForeignKey("Upload_BusBus_id");
                });

            modelBuilder.Entity("SRC_Travel_Agencies.Models.Upload_Bus", b =>
                {
                    b.HasOne("SRC_Travel_Agencies.Models.Bus_Category", "Category")
                        .WithMany()
                        .HasForeignKey("category_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SRC_Travel_Agencies.Models.Upload_Bus", b =>
                {
                    b.Navigation("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
